//_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
//_\source top.tlv 41

//_\SV
   // Include Tiny Tapeout Lab.
   // Included URL: "https://raw.githubusercontent.com/os-fpga/Virtual-FPGA-Lab/35e36bd144fddd75495d4cbc01c4fc50ac5bde6f/tlv_lib/tiny_tapeout_lib.tlv"// Included URL: "https://raw.githubusercontent.com/os-fpga/Virtual-FPGA-Lab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlv_lib/fpga_includes.tlv"
//_\source top.tlv 155

//_\SV

// ================================================
// A simple Makerchip Verilog test bench driving random stimulus.
// Modify the module contents to your needs.
// ================================================

module top(input logic clk, input logic reset, input logic [31:0] cyc_cnt, output logic passed, output logic failed);
   // Tiny tapeout I/O signals.
   logic [7:0] ui_in, uo_out;
   
   logic [31:0] r;  // a random value
   always @(posedge clk) r <= 0;
   assign ui_in = r[7:0];
   
   logic ena = 1'b0;
   logic rst_n = ! reset;

   /*
   // Or, to provide specific inputs at specific times (as for lab C-TB) ...
   // BE SURE TO COMMENT THE ASSIGNMENT OF INPUTS ABOVE.
   // BE SURE TO DRIVE THESE ON THE B-PHASE OF THE CLOCK (ODD STEPS).
   // Driving on the rising clock edge creates a race with the clock that has unpredictable simulation behavior.
   initial begin
      #1  // Drive inputs on the B-phase.
         ui_in = 8'h0;
      #10 // Step 5 cycles, past reset.
         ui_in = 8'hFF;
      // ...etc.
   end
   */

   // Instantiate the Tiny Tapeout module.
   tt_um_template tt(.*);

   //assign passed = top.cyc_cnt > 60;
   assign passed = top.cyc_cnt > 1000;
   assign failed = 1'b0;
endmodule


// Provide a wrapper module to debounce input signals if requested.

//_\SV



// =======================
// The Tiny Tapeout module
// =======================

module tt_um_template (
    input  wire [7:0] ui_in,    // Dedicated inputs - connected to the input switches
    output wire [7:0] uo_out,   // Dedicated outputs - connected to the 7 segment display
    /*   // The FPGA is based on TinyTapeout 3 which has no bidirectional I/Os (vs. TT6 for the ASIC).
    input  wire [7:0] uio_in,   // IOs: Bidirectional Input path
    output wire [7:0] uio_out,  // IOs: Bidirectional Output path
    output wire [7:0] uio_oe,   // IOs: Bidirectional Enable path (active high: 0=input, 1=output)
    */
    input  wire       ena,      // will go high when the design is enabled
    input  wire       clk,      // clock
    input  wire       rst_n     // reset_n - low to reset
);
   wire reset = ! rst_n;

// ---------- Generated Code Inlined Here (before 1st \TLV) ----------
// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// (Installed here: /usr/local/mono/sandpiper/distro.)
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)


genvar digit, input_label, leds, switch;


//
// Signals declared top-level.
//

// For $slideswitch.
logic [7:0] L0_slideswitch_a0;

// For $sseg_decimal_point_n.
logic L0_sseg_decimal_point_n_a0;

// For $sseg_digit_n.
logic [7:0] L0_sseg_digit_n_a0;

// For $sseg_segment_n.
logic [6:0] L0_sseg_segment_n_a0;

// For /fpga_pins/fpga|timer$clk.
logic FpgaPins_Fpga_TIMER_clk_a0;

// For /fpga_pins/fpga|timer$cnt1.
logic [7:0] FpgaPins_Fpga_TIMER_cnt1_a1,
            FpgaPins_Fpga_TIMER_cnt1_a2;

// For /fpga_pins/fpga|timer$cnt2.
logic [7:0] FpgaPins_Fpga_TIMER_cnt2_a1,
            FpgaPins_Fpga_TIMER_cnt2_a2;

// For /fpga_pins/fpga|timer$digit.
logic [6:0] FpgaPins_Fpga_TIMER_digit_a1;

// For /fpga_pins/fpga|timer$dsel.
logic [0:0] FpgaPins_Fpga_TIMER_dsel_a1;

// For /fpga_pins/fpga|timer$hexout.
logic [6:0] FpgaPins_Fpga_TIMER_hexout_a1;

// For /fpga_pins/fpga|timer$pulse.
logic FpgaPins_Fpga_TIMER_pulse_a1,
      FpgaPins_Fpga_TIMER_pulse_a2;

// For /fpga_pins/fpga|timer$reset.
logic FpgaPins_Fpga_TIMER_reset_a0,
      FpgaPins_Fpga_TIMER_reset_a1;




   //
   // Scope: /fpga_pins
   //


      //
      // Scope: /fpga
      //


         //
         // Scope: |timer
         //

            // Staging of $cnt1.
            always_ff @(posedge clk) FpgaPins_Fpga_TIMER_cnt1_a2[7:0] <= FpgaPins_Fpga_TIMER_cnt1_a1[7:0];

            // Staging of $cnt2.
            always_ff @(posedge clk) FpgaPins_Fpga_TIMER_cnt2_a2[7:0] <= FpgaPins_Fpga_TIMER_cnt2_a1[7:0];

            // Staging of $pulse.
            always_ff @(posedge clk) FpgaPins_Fpga_TIMER_pulse_a2 <= FpgaPins_Fpga_TIMER_pulse_a1;

            // Staging of $reset.
            always_ff @(posedge clk) FpgaPins_Fpga_TIMER_reset_a1 <= FpgaPins_Fpga_TIMER_reset_a0;








//
// Debug Signals
//

   if (1) begin : DEBUG_SIGS_GTKWAVE

      (* keep *) logic [7:0] \@0$slideswitch ;
      assign \@0$slideswitch = L0_slideswitch_a0;
      (* keep *) logic  \@0$sseg_decimal_point_n ;
      assign \@0$sseg_decimal_point_n = L0_sseg_decimal_point_n_a0;
      (* keep *) logic [7:0] \@0$sseg_digit_n ;
      assign \@0$sseg_digit_n = L0_sseg_digit_n_a0;
      (* keep *) logic [6:0] \@0$sseg_segment_n ;
      assign \@0$sseg_segment_n = L0_sseg_segment_n_a0;

      //
      // Scope: /digit[0:0]
      //
      for (digit = 0; digit <= 0; digit++) begin : \/digit 

         //
         // Scope: /leds[7:0]
         //
         for (leds = 0; leds <= 7; leds++) begin : \/leds 
            (* keep *) logic  \//@0$viz_lit ;
            assign \//@0$viz_lit = L1_Digit[digit].L2_Leds[leds].L2_viz_lit_a0;
         end
      end

      //
      // Scope: /fpga_pins
      //
      if (1) begin : \/fpga_pins 

         //
         // Scope: /fpga
         //
         if (1) begin : \/fpga 

            //
            // Scope: |timer
            //
            if (1) begin : P_timer
               (* keep *) logic  \///@0$clk ;
               assign \///@0$clk = FpgaPins_Fpga_TIMER_clk_a0;
               (* keep *) logic [7:0] \///@1$cnt1 ;
               assign \///@1$cnt1 = FpgaPins_Fpga_TIMER_cnt1_a1;
               (* keep *) logic [7:0] \///@1$cnt2 ;
               assign \///@1$cnt2 = FpgaPins_Fpga_TIMER_cnt2_a1;
               (* keep *) logic [6:0] \///@1$digit ;
               assign \///@1$digit = FpgaPins_Fpga_TIMER_digit_a1;
               (* keep *) logic [0:0] \///@1$dsel ;
               assign \///@1$dsel = FpgaPins_Fpga_TIMER_dsel_a1;
               (* keep *) logic [6:0] \///@1$hexout ;
               assign \///@1$hexout = FpgaPins_Fpga_TIMER_hexout_a1;
               (* keep *) logic  \///@1$pulse ;
               assign \///@1$pulse = FpgaPins_Fpga_TIMER_pulse_a1;
               (* keep *) logic  \///@0$reset ;
               assign \///@0$reset = FpgaPins_Fpga_TIMER_reset_a0;
            end
         end
      end

      //
      // Scope: /switch[7:0]
      //
      for (switch = 0; switch <= 7; switch++) begin : \/switch 
         (* keep *) logic  \/@0$viz_switch ;
         assign \/@0$viz_switch = L1_Switch[switch].L1_viz_switch_a0;
      end


   end

// ---------- Generated Code Ends ----------
//_\TLV
   /* verilator lint_off UNOPTFLAT */
   // Connect Tiny Tapeout I/Os to Virtual FPGA Lab.
   //_\source /raw.githubusercontent.com/osfpga/VirtualFPGALab/35e36bd144fddd75495d4cbc01c4fc50ac5bde6f/tlvlib/tinytapeoutlib.tlv 76   // Instantiated from top.tlv, 225 as: m5+tt_connections()
      assign L0_slideswitch_a0[7:0] = ui_in;
      assign L0_sseg_segment_n_a0[6:0] = ~ uo_out[6:0];
      assign L0_sseg_decimal_point_n_a0 = ~ uo_out[7];
      assign L0_sseg_digit_n_a0[7:0] = 8'b11111110;
   //_\end_source

   // Instantiate the Virtual FPGA Lab.
   //_\source /raw.githubusercontent.com/osfpga/VirtualFPGALab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlvlib/fpgaincludes.tlv 307   // Instantiated from top.tlv, 228 as: m5+board(/top, /fpga, 7, $, , my_design)
      
      //_\source /raw.githubusercontent.com/osfpga/VirtualFPGALab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlvlib/fpgaincludes.tlv 355   // Instantiated from /raw.githubusercontent.com/osfpga/VirtualFPGALab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlvlib/fpgaincludes.tlv, 309 as: m4+thanks(m5__l(309)m5_eval(m5_get(BOARD_THANKS_ARGS)))
         //_/thanks
            
      //_\end_source
      
   
      // Board VIZ.
   
      // Board Image.
      
      //_/fpga_pins
         
         //_/fpga
            //_\source top.tlv 48   // Instantiated from /raw.githubusercontent.com/osfpga/VirtualFPGALab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlvlib/fpgaincludes.tlv, 340 as: m4+my_design.
            
            
            
               // ==================
               // |                |
               // | YOUR CODE HERE |
               // |                |
               // ==================
            
               // Note that pipesignals assigned here can be found under /fpga_pins/fpga.
            
               // default clock is 20 Mhz
               //_|timer
            
                  //_@0
                     assign FpgaPins_Fpga_TIMER_reset_a0 = reset;
                     assign FpgaPins_Fpga_TIMER_clk_a0 = clk;
            
                  //_@0
                     // Board inputs
                     //$binputs[3:0] = *ui_in[3:0];
                     //$out0[3:0] = 4'h0; //4'h1;
                     //$out1[3:0] = 4'h0;
            
            
            
                  //_@1
                     //$digit[6:0] = $out0[6:0];
            
                     // decode inputs
                     //$rreset[0:0] = $binputs[0:0];
                     //$start[0:0] = $binputs[1:1];
                     //$pause[0:0] = $binputs[2:2];
                     //$resume[0:0] = $binputs[3:3];
            
                     // example constraining max count to '0c'
                     //$cnt[7:0] = $reset == 1'b1 ? 8'b0 :
                     //            $cnt[7:0] == 7'h0c   ? $cnt[7:0] :
                     //            >>1$cnt[7:0] + 1;
            
                     // example for counter rolling over
                     assign FpgaPins_Fpga_TIMER_cnt1_a1[7:0] = FpgaPins_Fpga_TIMER_reset_a1 == 1'b1 ? 8'b0 :
                                 FpgaPins_Fpga_TIMER_cnt1_a2[7:0] + 1;
                     // counter defaults to roller over from ff to 00
            
                     // 2nd stage counter
                     assign FpgaPins_Fpga_TIMER_cnt2_a1[7:0] = FpgaPins_Fpga_TIMER_reset_a1 == 1'b1 ? 8'b0 :
                                  FpgaPins_Fpga_TIMER_cnt1_a1[7:0] == 8'hff ? FpgaPins_Fpga_TIMER_cnt2_a2[7:0] + 1 :
                                  FpgaPins_Fpga_TIMER_cnt2_a2[7:0];
            
                     // example for generating a pulse ... $pulse inverts everytime $cnt1=FF
                     assign FpgaPins_Fpga_TIMER_pulse_a1 = FpgaPins_Fpga_TIMER_reset_a1 == 1'b1 ? 1'b0 :
                              FpgaPins_Fpga_TIMER_cnt1_a1[7:0] == 8'hff ? ! FpgaPins_Fpga_TIMER_pulse_a2 :
                              FpgaPins_Fpga_TIMER_pulse_a2;
            
                     //10 millisecond counter
                     //$cnt3[31:0] = $reset == 1'b1 ? 32'b0 :
                     //              $cnt3[31:0] == 32'h00030d40 ? 32'b0 :
                     //              >>1$cnt3[31:0] + 1;
            
            
                     //$digit1[3:0] = $out1[3:0];
                     //$dsel[0:0] = 1'b0; // select digit 0
                           //= 1'b1; // select digit 1
            
                     // this works
                     assign FpgaPins_Fpga_TIMER_dsel_a1[0:0] = 1'b1;
                     //$dsel[0:0] = $pulse;
                     //$dsel[0:0] = $reset == 1'b1 ? 1'b0 :
                     //             $cnt1[7:0] == 8'hff ? ! >>1$dsel : // works
                                  //$cnt3[7:0] == 8'hff ? ! >>1$dsel : // works
                                  //$cnt3[31:0] == 8'hff ? ! >>1$dsel :
                     //             $dsel[0:0];
            
            
            
                     //$dsel[0:0] = $reset == 1'b1 ? 1'b0 :
                     //             $cnt3[31:0] == 8'hff ? 1'b1 : // 1'b1 // !dsel[0:0]
                     //             //$cnt3[31:0] == 32'hXXXXXXff ? 1'b1 :
                     //             1'b0;
            
                     //             $cnt3[31:0] == 32'h0000000ff ? !dsel[0:0] :
                     //             1b'0;
            
                     assign FpgaPins_Fpga_TIMER_digit_a1[6:0] = 7'h00;
            
                     //$hexout[7:7] = $dsel[0:0];
                     assign FpgaPins_Fpga_TIMER_hexout_a1[6:0] = FpgaPins_Fpga_TIMER_digit_a1 == 7'h00 ? 7'b0111111 :
                                    FpgaPins_Fpga_TIMER_digit_a1 == 7'h01 ? 7'b0000110 :
                                    FpgaPins_Fpga_TIMER_digit_a1 == 7'h02 ? 7'b1011011 :
                                    FpgaPins_Fpga_TIMER_digit_a1 == 7'h03 ? 7'b1001111 :
                                    FpgaPins_Fpga_TIMER_digit_a1 == 7'h04 ? 7'b1100110 :
                                    FpgaPins_Fpga_TIMER_digit_a1 == 7'h05 ? 7'b1101101 :
                                    FpgaPins_Fpga_TIMER_digit_a1 == 7'h06 ? 7'b1111101 :
                                    FpgaPins_Fpga_TIMER_digit_a1 == 7'h07 ? 7'b0000111 :
                                    FpgaPins_Fpga_TIMER_digit_a1 == 7'h08 ? 7'b1111111 :
                                                      7'b1101111 ;
            
                     // connect to top level I/O
                     assign uo_out[6:0] = FpgaPins_Fpga_TIMER_hexout_a1[6:0];
                     assign uo_out[7:7] = FpgaPins_Fpga_TIMER_dsel_a1[0:0]; //$hexout[7:7];
            
            
               // Connect Tiny Tapeout outputs. Note that uio_ outputs are not available in the Tiny-Tapeout-3-based FPGA boards.
               assign uo_out = 8'b0;
               
               
            //_\end_source
   
      // LEDs.
      
   
      // 7-Segment
      //_\source /raw.githubusercontent.com/osfpga/VirtualFPGALab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlvlib/fpgaincludes.tlv 395   // Instantiated from /raw.githubusercontent.com/osfpga/VirtualFPGALab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlvlib/fpgaincludes.tlv, 346 as: m4+fpga_sseg.
         for (digit = 0; digit <= 0; digit++) begin : L1_Digit //_/digit
            
            for (leds = 0; leds <= 7; leds++) begin : L2_Leds //_/leds

               // For $viz_lit.
               logic L2_viz_lit_a0;

               assign L2_viz_lit_a0 = (! L0_sseg_digit_n_a0[digit]) && ! ((leds == 7) ? L0_sseg_decimal_point_n_a0 : L0_sseg_segment_n_a0[leds % 7]);
               
            end
         end
      //_\end_source
   
      // slideswitches
      //_\source /raw.githubusercontent.com/osfpga/VirtualFPGALab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlvlib/fpgaincludes.tlv 454   // Instantiated from /raw.githubusercontent.com/osfpga/VirtualFPGALab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlvlib/fpgaincludes.tlv, 349 as: m4+fpga_switch.
         for (switch = 0; switch <= 7; switch++) begin : L1_Switch //_/switch

            // For $viz_switch.
            logic L1_viz_switch_a0;

            assign L1_viz_switch_a0 = L0_slideswitch_a0[switch];
            
         end
      //_\end_source
   
      // pushbuttons
      
   //_\end_source
   // Label the switch inputs [0..7] (1..8 on the physical switch panel) (top-to-bottom).
   //_\source /raw.githubusercontent.com/osfpga/VirtualFPGALab/35e36bd144fddd75495d4cbc01c4fc50ac5bde6f/tlvlib/tinytapeoutlib.tlv 82   // Instantiated from top.tlv, 230 as: m5+tt_input_labels_viz(⌈"UNUSED", "UNUSED", "UNUSED", "UNUSED", "UNUSED", "UNUSED", "UNUSED", "UNUSED"⌉)
      for (input_label = 0; input_label <= 7; input_label++) begin : L1_InputLabel //_/input_label
         
      end
   //_\end_source

//_\SV
endmodule


// Undefine macros defined by SandPiper.
`undef BOGUS_USE
